# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Flota

stages:
  - stage: "Build"
    displayName: "Build api server"
    jobs:
      - job: "Build"
        pool:
          vmImage: "windows-latest"

        variables:
          - name: NUGET.PLUGIN.HANDSHAKE.TIMEOUT.IN.SECONDS
            value: 60
          - name: NUGET.PLUGIN.REQUEST.TIMEOUT.IN.SECONDS
            value: 60
          - name: buildConfiguration
            value: "Release"

        steps:

          - task: NuGetAuthenticate@1

          - task: DotNetCoreCLI@2
            displayName: "Build"
            inputs:
              command: "build"
              projects: "Flota/api/*.csproj"
              arguments: "--configuration $(BuildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "Publish project"
            inputs:
              command: "publish"
              publishWebProjects: false
              projects: "Flota/api/*.csproj"
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              modifyOutputPath: false
          - task: PublishBuildArtifacts@1
            displayName: "Upload artifacts"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"